name: Angular Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Chrome
      run: sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: npm install

    - name: Run tests with ChromeHeadless and check coverage
      env:
        KARMA_BROWSER: ChromeHeadless
      run: npm test -- --watch=false --code-coverage

    - name: Upload coverage report if >= 90%
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
